# Generated by Django 4.0.6 on 2022-07-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=20, null=True),
        ),
    ]
