# Generated by Django 4.0.5 on 2022-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
