# Generated by Django 4.0.5 on 2022-07-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_alter_profile_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not sure', 'not sure')], max_length=100, null=True),
        ),
    ]
