# Generated by Django 4.0.6 on 2023-04-27 05:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('wear', 'wear'), ('footwear', 'footwear')], max_length=20, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(null=True, upload_to='product_image/')),
                ('item_validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_table',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_cashout', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.CharField(max_length=11)),
                ('cashout', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=1)),
                ('price_item', models.FloatField(blank=True)),
                ('purchased', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_agent', models.IntegerField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
