# Generated by Django 4.0.5 on 2022-07-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_product_image_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
    ]
