# Generated by Django 4.0.5 on 2022-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_productname_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='item_validation',
            field=models.BooleanField(default=False),
        ),
    ]
