# Generated by Django 4.0.5 on 2022-07-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_remove_product_product_image_product_item_validation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_validation',
            new_name='validation',
        ),
    ]
