# Generated by Django 4.0.5 on 2022-07-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='validation',
            new_name='item_validation',
        ),
    ]
