# Generated by Django 4.0.5 on 2022-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='checkOut',
            new_name='delivered',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_agent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
